---
title: "Gather and filter metanalysis"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---


# Introduction


# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
#v.01
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 14))

# Set seed for reproducibility
set.seed(13)
# Color blind friendly pallet
cbp1 <- c("#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")

scale_fill_discrete <- function(...) {
  scale_fill_manual(..., values = cbp1)
}
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = cbp1)
}

# Set output directory
d.out <- params$d.out
rm(params)
```


## Library

```{r}
library(tidyverse)
library(foreach)
library(doParallel)
library(qqman)
```

## Paths
```{r}
test.dir <- "/work_ifs/sukmb447/projects/skin.mgwas/results/2.statistical.tests/1.beta.diversity/results/"
files <- list.files(test.dir)

# Import lambda functions
source("/work_ifs/sukmb447/projects/skin.mgwas/scripts/functions/estlamb.R")
source("/work_ifs/sukmb447/projects/skin.mgwas/scripts/functions/estlambda/estlambda.R")
source("/work_ifs/sukmb447/projects/skin.mgwas/scripts/functions/get.lambda.filtered.R")
source("/work_ifs/sukmb447/projects/skin.mgwas/scripts/functions/get.lambda.R")
indexes <- data.frame(index.1 = c(1,3,4), index.2 = c(2,6,5), microenv = c("Moist", "Dry", "Sebaceous")) %>% 
  mutate(meta.id = paste0(index.1, index.2))
```

# Function get data of individual tests

```{r}
# make function to run inside paralellel for loop
get.data <- function(x, df.i){
  chr.i <- df.i[x, "chr"]
  index.1.i <- df.i[x, "index.1"]
  index.2.i <- df.i[x, "index.2"]
  meta.id.i <- df.i[x, "meta.id"]
  
  # Get cohort 1
  f1 <- files[str_detect(files, paste0("index", index.1.i, ".","chr", chr.i, ".betatests.rds"))] %>% 
    paste0(test.dir, .) %>% 
    readRDS() %>% 
    select(snp.name, A, B, AA, AB, BB, n, stat, P)
  
  colnames(f1)[2:ncol(f1)] <- paste0(colnames(f1)[2:ncol(f1)], ".index1")

  # Get cohort 2
  f2 <- files[str_detect(files, paste0("index", index.2.i, ".","chr", chr.i, ".betatests.rds"))] %>% 
    paste0(test.dir, .) %>% 
    readRDS() %>% 
    select(snp.name, A, B, AA, AB, BB, n, stat, P)
  
  colnames(f2)[2:ncol(f2)] <- paste0(colnames(f2)[2:ncol(f2)], ".index2")
  
  #Join cohorts
  f <- full_join(f1, f2, by = "snp.name") %>% 
    mutate(meta.id = meta.id.i) %>% 
    left_join(indexes, by = c("meta.id"))
    
  return(f)
}

```


# Function to import and filter metaanalysis

```{r}
read.and.filter <- function(meta.id, filter){
  
  # Get individual tests
  # Add single tests information
  
  df.i <- data.frame(chr = 1:22, meta.id = rep(meta.id, 22)) %>% 
    left_join(indexes, by = "meta.id")

  tests.res <- NULL
  for (x in 1:nrow(df.i)){
    tests.res[[x]] <- get.data(x, df.i)
  }
  
  tests.res <- tests.res %>% 
    bind_rows() %>%
    separate(snp.name, into = c("chr", "position"), sep = ":", remove = F) %>% 
    mutate(position = position %>% as.numeric,
           chr = chr %>% as.numeric()) %>% 
    arrange(chr, position)
  
  # Add meta-analysis results when necessary
  
  if(unique(df.i$microenv) != "Dry"){
    
  #read
  tb <- paste0("/work_ifs/sukmb447/projects/skin.mgwas/results/3.meta.analysis/1.microenv/1.beta.diversity/1.metaanalysis/indexes",meta.id,"/METAANALYSIS1.TBL") %>% 
    read.delim(., stringsAsFactors = F, sep = "\t", header = T)
  # format
  tb <- tb %>%
    rename("snp.name" = "MarkerName")
  
  meta <- left_join(tests.res, tb, by = "snp.name")
  rm(tests.res, tb)
  }else{
    meta <- tests.res
    rm(tests.res)
  }
  
  # Define P.meta and significance
  if(unique(df.i$microenv) != "Dry"){
    meta <- meta %>% 
      mutate(P.meta = P.value)
  }else{
    meta$P.meta <- with(meta, pmin(P.index1, P.index2))
  }
  
  # write formatted 
  f.name <- paste0(d.out, "/", "gathered.meta", meta.id, ".tsv")
  write_tsv(meta, f.name)
  system(paste("gzip", f.name))

  # calculate lambda
  
  l1 <- get.lambda(meta$P.meta)
  l2 <- get.lambda.filtered(meta, "chr", "position", "P.meta")
  lamb <- cbind(l1,l2) %>% 
    mutate(meta.id := meta.id)
  
  # Plot Manhattan
  
  paste0(d.out, "/", "gathered.meta", meta.id, ".man.jpeg") %>% 
    jpeg(width = 720, height = 480)
  manhattan(meta, chr = "chr", bp = "position",snp = "name", p = "P.meta")
  dev.off()
 
  # Plot qq
  
  paste0(d.out, "/", "gathered.meta", meta.id, ".qq.jpeg") %>% 
    jpeg(width = 720, height = 480)
  tryCatch({qq(meta$P.meta)},
           error = function(e) {NULL})
  dev.off()
  
  #filter
  meta <- meta %>% 
    filter(P.meta < filter)
  
  return(list(meta, lamb))
}

```


# Import results and Filter
```{r}
lamb <- NULL
res <- NULL
for (i in c("12", "36", "45")){ 
  res.i <- read.and.filter(i, 10^-5) # suggestive P-value
  res <- bind_rows(res, res.i[[1]])
  lamb <- bind_rows(lamb, res.i[[2]])
}

paste0(d.out, "/", "meta.lambda.tsv") %>% 
  write_tsv(lamb, .)
```


```{r}
res <- res %>% 
  filter(P.index1 < 0.05 & P.index2 < 0.05)
```

# Interesting locations
```{r}
res.filter <- res %>%  
  filter(P.meta < 5e-8) # genome wide P-value
```

# Write output

```{r}
paste0(d.out, "/", "gather.meta.suggestive.rds") %>% 
  saveRDS(res, .)
paste0(d.out, "/", "gather.meta.genomewide.rds") %>% 
  saveRDS(res.filter, .)
```


# Conclusion

# Session information

```{r}
sessionInfo()
```
