---
title: "Prepare beta-diversity data for tests"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
  index: "1"
---


# Introduction


# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
#v.01
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 14))

# Set seed for reproducibility
set.seed(13)
# Color blind friendly pallet
cbp1 <- c("#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")

scale_fill_discrete <- function(...) {
   scale_fill_manual(..., values = cbp1)
}
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = cbp1)
}

# Set output directory
d.out <- params$d.out
# Set session parameters
index <- params$index
chr <- params$chr

rm(params)
```


## Load libraries for the session

```{r}
library(ggplot2)
library(tidyverse)
library(phyloseq)
library(vegan)
```

## Import data
```{r}
ps <- readRDS("~/IKMB/projects/skin.mgwas/results/1.data.harmonization/3.microbiome.harmonized/phyloseq.rds")

pca <- paste0("~/IKMB/projects/skin.mgwas/results/1.data.harmonization/2.genotype/PopGen_and_KORA.harmonized.all.pca.eigenvec") %>% 
  read.delim(sep = " ", header = F) %>% 
  column_to_rownames("V1") %>% 
  magrittr::set_colnames(c("Genotype_ID", paste0("PCA", 1:20)))
```


# Select site and cohort

```{r}
ps <- subset_samples(ps, index == .GlobalEnv$index) %>% 
  prune_taxa(taxa_sums(.) > 0, .)
```
#Add Sync pca to ps object

```{r}
#extract meta and add pca
meta <- sample_data(ps) %>% 
  data.frame() %>% 
  left_join(pca %>% select(-paste0("PCA", 11:20)), by = "Genotype_ID")
rownames(meta) <- meta$NGS_ID
#check
checkpoint <- identical(meta %>% pull(NGS_ID), sample_data(ps) %>% pull(NGS_ID))
if(!checkpoint){quit()}else{print("ok");rm(checkpoint)}
# add to ps
sample_data(ps) <- sample_data(meta)
rm(meta)
```


# Write output

```{r}

# Make list
paste0(d.out, "/", "index", index, ".ps", ".rds") %>% 
  saveRDS(ps, .)
```


# Conclusion

# Session information

```{r}
sessionInfo()
```
