---
title: "Final plot"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      toc_float: true
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---
# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
#v.02
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               #dev=c("png",'pdf'),
               dev=c("png"),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)

# Set ggplot2 them as black and with
library("ggplot2")
library(ggthemes)
theme_set(theme_few(base_size = 16))
# Set seed for reproducibility
set.seed(13)

# Color blind friendly pallet
cbp1 <- c("#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black")

scale_fill_discrete <- function(...) {
  scale_fill_manual(..., values = cbp1)
}
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = cbp1)
}

# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session

```{r}
library(tidyverse)
library(phyloseq)
library(grid)
library(gridExtra)
library(gtable)
library(ggplot2)
library(tidyverse)
library(phyloseq)
library(reshape2)
library(ggrepel)
library(data.table)
library(gdata)
```

## Import data
```{r}
to_plot <- readRDS("/home/lsilva/IKMB/projects/skin.mgwas/results/5.plot.manhattan/plot.df.RDS")
snp_stats_plot <- readRDS("/home/lsilva/IKMB/projects/skin.mgwas/results/4.fine.mapping/1.meta/1.microenv/2.annotate.data/combined/plot.stats.df.rds")
# Summary of associations
plot_loci_microenv_df <- snp_stats_plot$plot_loci_microenv
plot_level_df <- snp_stats_plot$plot_level
plot_genera_df <- snp_stats_plot$plot_genera
```
# Make bottom plots
## Plots

```{r}
# Percentage of the plot
plot_loci_microenv <- 
  plot_loci_microenv_df %>% 
  ggplot(aes(x = fct_reorder(microenv, desc(n)), y = n)) +
  geom_col(aes(fill = microenv)) +
  ggpubr::rotate_x_text(45) +
  labs(x = "Microenv.", y = "n") +
  scale_fill_manual(values = cbp1[c(2,1,3)]) +
  theme(legend.position = "none")
plot_loci_microenv

plot_level <- plot_level_df %>% 
  ggplot(aes(x = fct_reorder(level, desc(n)), y = n)) +
  geom_col(fill = "darkgrey") +
  ggpubr::rotate_x_text(angle = 45) +
  labs(x = "Microb. features", y = "n") 
plot_level


plot_genera <- plot_genera_df %>% 
  ggplot(aes(x = fct_reorder(Genus, desc(n)), y = n)) +
  geom_col(fill = "darkgrey") +
  ggpubr::rotate_x_text(angle = 45) +
  labs(x = "Sub-family features", y = "n") +
  theme(axis.text.x = element_text(face = "italic"))

```

## Plot them all together
```{r, fig.width = 16}
bottom <- ggpubr::ggarrange(
  plot_loci_microenv,
  plot_level, 
  plot_genera,
  ncol = 3,
  labels = c("b", "c", "d"),
  widths = c(0.8, 1.2, 1.2))
bottom
```

# Manhattan 

## Main plot
```{r, fig.width = 16, fig.height = 9}
# Prepare X axis
axisdf <- to_plot %>% 
  group_by(chr) %>% 
  summarize(center=(max(positioncum) + min(positioncum)) / 2 )

# Change labels
to_plot <- to_plot %>% 
  mutate(id_rsid = if_else(!is.na(label),
                           paste0(label, ": ", rsID),
                           NA_character_))

mann_plot <- ggplot(to_plot, aes(x = positioncum, y = -log10(P), label = id_rsid)) +
  #Add all points that are not annotated
  geom_point(data = to_plot %>%
               filter(is.na(label)),
             color= to_plot %>%
               filter(is.na(label)) %>%
               .[, col],
             alpha = 0.8,
             size = 1) +
  # # Add annotated points
  geom_point(data = to_plot %>% filter(!is.na(label)), 
             aes(color = microenv),
             size = 3) +
  scale_y_continuous(limits = c(1, 12), expand = c(-0.05, 0.01)) +
  #c(-0.01, 0.01)
  # custom X axis
  scale_x_continuous(label = axisdf$chr, 
                     breaks = axisdf$center,
                     expand = c(0.01, 0.01)) +
  # Add label keys
  geom_text_repel(data = to_plot %>%
                    filter(!is.na(label)),
                  aes(label = id_rsid),
                  size = 3.5,
                  angle = 90,
                  point.padding=unit(1,'lines'),
                  angle = 45, # vertical names
                  vjust = 0.5,# align
                  direction = "x", # allow to move only at the x axis
                  max.iter = 1e4,
                  force_pull = 0,
                  #Add some line aesthetics
                  segment.curvature = -1e-20, # add a slight curve
                  segment.color = "grey",
                  segment.linetype = 4,
                  min.segment.length = 0, #always draw line
                  # Limit area of labels
                  xlim = c(-Inf, Inf),
                  ylim = c(9.4, Inf)) +
  # Mod the theme
  theme(legend.position = "bottom", 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_blank(),
        legend.margin = margin(0,0,0,0),
        legend.box.margin = margin(0,0,-3,0)) +
  # add cut-offs
  geom_hline(yintercept = -log10(5e-8),
             linetype = "dashed", 
             color = "firebrick", size=0.7) +
  geom_hline(yintercept = -log10(1e-5),
             linetype = "dashed", 
             color = "dodgerblue", size=0.7) +
  # add labels
  labs(x = "Chromosome", y = bquote(-log[10](P[Meta]))) +
  # modify guide names
  guides(color=guide_legend(title="Microenv.")) +
  ggpubr::rotate_x_text(70) 

mann_plot
```


## Labels

```{r}
label <- to_plot %>% 
  filter(!is.na(tax)) %>% 
  select(chr, label, label.key) %>%
  mutate(label.key = sub(" : ", ":", label.key)) %>% 
  mutate(label.key = sub(" : ", " - ", label.key)) %>% 
  mutate(label.key = sub(":-", " - ", label.key)) %>% 
  mutate(label.key = gsub(";", ",", label.key)) %>% 
  mutate(label = paste(label, label.key, sep = " - ")) %>% 
  select(chr, label)

# Legens will be presented in three columns
nchunks <- (nrow(label)/2) %>%  round()
label <- label %>% 
  pull(label) %>% 
  split(., ceiling(seq_along(.)/nchunks))

# Get table with the labels
label.df = cbindX(data.frame(l1 = label[[1]]),
                  data.frame(l2 = label[[2]]))
label.df[is.na(label.df)] <- ""

## Tweak the aesthetics of the table in the plot
tt <- ttheme_default(base_size = 11, 
                     core=list(fg_params=list(hjust = 0,
                                              x = 0,
                                              cex = 1.05), # adjust to left
                               bg_params = list(
                                 #fill = "grey90", # background color
                                 col = "white")),
                     padding = unit(c(4, 4), "mm")) # line color
# Make table grob object
gtable <- tableGrob(label.df, rows=NULL, cols = NULL, theme = tt)

legends <- ggplot() + 
  theme_void(base_size = 22) +
  annotation_custom(gtable, 
                    xmin = -Inf,
                    xmax = Inf,
                    ymin = -Inf,
                    ymax = Inf)

legends
```

## Plot mannhattan and legends
```{r, fig.width = 14, fig.height = 18}
man_legend <- ggpubr::ggarrange(mann_plot + 
                                  theme(plot.margin = unit(c(0,1,0,1), 
                                                           "lines")),
                                legends + 
                                  theme(plot.margin = unit(c(-1,0,0,0), 
                                                           "lines")),
                                nrow = 2, heights = c(4.5,3.5))
man_legend
```


# Plot all

```{r, fig.width = 12, fig.height = 9}
ggpubr::ggarrange(mann_plot,
                  bottom, 
                  nrow = 2, 
                  heights = c(5.5, 2.5),
                  labels = c("a", ""))
```

# Session information

```{r}
sessionInfo()
```
